# Generated by Django 3.1.5 on 2021-01-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210105_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(blank=True, default='this is awesome'),
            preserve_default=False,
        ),
    ]
